### ISSUE TITLE
Unable to access token in onTokenSuccess 

### ISSUE THREAD

**Issue by tonjohn** [survirtual/vue-adal#10]
I need to add the token to `http.defaults.headers.common['Authorization']` in `onTokenSuccess ` but it does not appear to be passed in.

**Comment by survirtual** [comment]
You're right; the callback doesn't return anything.  The original intention was to just notify that the attempt to get a token was completed, but I don't see any harm in added an err on failure or token on success.

**Comment by survirtual** [comment]
Merged #13 : added token as third parameter to onTokenSuccess
