### ISSUE TITLE
this.$adal not available when using typescript

### ISSUE THREAD

**Issue by abaga129** [survirtual/vue-adal#16]
First of all thanks for this library! It has been extremely useful.

I chose to use typescript with vue and for some reason I cannot access the adal plugin by using `this`.  I'm still able to access any of the necessary methods by importing the `AuthenticationContext` and using it directly.

Here is how I'm installing the plugin
```ts
import { default as adal } from 'vue-adal'

Vue.use(adal, {
  config: {
    tenant: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    clientId: process.env.AD_CLIENT_ID,
    redirectUri: process.env.AD_REDIRECT_URI,
    cacheLocation: 'sessionStorage'
  },
  requireAuthOnInitialize: true,
  router: router
});
```
This is what I get when I try to call `this.$adal`
![image](https://user-images.githubusercontent.com/8194039/44350206-6439e200-a464-11e8-9371-0494fc7351db.png)

Any ideas on what might be the problem?

**Comment by survirtual** [comment]
You will need [augment the type definition for Vue](https://vuejs.org/v2/guide/typescript.html#Augmenting-Types-for-Use-with-Plugins).

I haven't added / have no plan to add typescript support for this library.  Would welcome a pull request :)

**Comment by abaga129** [comment]
Thanks for the response! I might make a pull request if I get a chance.  If anyone using typescript happens upon this, you can import `AuthenticationContext` and using it instead of `this.$adal`
