### ISSUE TITLE
How to obtain a bearer token?

### ISSUE THREAD

**Issue by profabe** [survirtual/vue-adal#2]
First of all your code works great so far - good job! I only struggle with acquiring the token to sent as JWT Bearer Token. Can you help? What am I doing wrong? Thank you!

~~~~ 
import adal from "vue-adal"

// Some other code

axios.interceptors.request.use(function (config) {
    adal.acquireToken().then(token => {
        config.headers = {
            'Content-Type': 'application/json',
            'Ocp-Apim-Subscription-Key': 'api key',
            'Authorization': 'Bearer ' + token
        }
    });

    return config;
}, function (error) {
    return Promise.reject(error);
});
~~~~ 

**Error message:**
actions.js:42 Uncaught (in promise) TypeError: _vueAdal2.default.acquireToken is not a function
    at Object.defineProperty.value (actions.js:42)
    at <anonymous>

**Comment by survirtual** [comment]
Adal's promises are turned into callbacks.  I wrote this library for work and people seem to have a lot of trouble with promises and observables, so tried to keep it simple.  

Do the following to get a bearer token:

```
adal.acquireToken(<resource-id>, (err, token) => {
  if (err) {
    // Handle error
    return;
  }
   // Have a token
})
```


With axios, I like to maintain an http client per endpoint with a properly configured auth header appropriate for the endpoint pre-configured.  In the event that I get a 401 after making the call due to an expired token -- this uses the implicit flow, after all, so those tokens last about 2 hours -- I'll go through the cycle of auth necessary to get access again.

Intending to have the library handle most of this automatically in the future.

**Comment by Sobient** [comment]
Have a look at https://github.com/sandrinodimattia/axios-token-interceptor if you want to auto-inject tokens into every axios request.

**Comment by profabe** [comment]
Many thanks for your quick feedback - I appreciate it a lot.

I still get the following error:
```
actions.js:37 Uncaught (in promise) TypeError: _adalAngular2.default.acquireToken is not a function
    at Object.defineProperty.value (actions.js:37)
    at <anonymous>
```

Here is the updated code located in actions.js, which defines my action in Vuex:

```javascript
import adal from "adal-angular";

...

axios.interceptors.request.use(function (config) {
    adal.acquireToken('https://fwohlschlaegerreply687.onmicrosoft.com', (err, token) => {
        config.headers = {
            'Content-Type': 'application/json',
            'Ocp-Apim-Subscription-Key': 'api key',
            'Authorization': 'Bearer ' + token
        }
    });
        
    return config;
}, function (error) {
    return Promise.reject(error);
});
```

Not sure what I am doing wrong...

**Comment by profabe** [comment]
I solved the issue by attaching the vue application to the window object:

```javascript
window.App = new Vue({
    el: '#app',
    store,
    router,
    template: '<App/>',
    components: { App }
})
```

Following I can access the $adal plugin to acquire the token later on:

```javascript
// Azure Active Directory authentication
axios.interceptors.request.use(function (config) {
    let authenticationContext = window.App.$adal.adalContext    // Obtain adal reference via window object
    authenticationContext.acquireToken(authenticationContext.config.clientId, (err, token) => {
        config.headers = {
            'Content-Type': 'application/json',
            'Ocp-Apim-Subscription-Key': 'api key',
            'Authorization': 'Bearer ' + token
        }
    })
        
    return config
}, function (error) {
    return Promise.reject(error)
})
```
One last question: Isn't adal.js already handling the silent refresh of the token automatically  for you? See [here ](https://stackoverflow.com/questions/37535366/acquiring-new-access-token-using-refresh-token-adal-js?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa) and [here](https://github.com/AzureAD/azure-activedirectory-library-for-js/issues/215) for reference.

**Comment by survirtual** [comment]
Do an import of the Authentication Context from 'vue-adal' to call acquireToken, like so:

```
import { AuthenticationContext } from 'vue-adal'

...

AuthenticationContext.acquireToken(authenticationContext.config.clientId, (err, token) => {
        config.headers = {
            'Content-Type': 'application/json',
            'Ocp-Apim-Subscription-Key': 'api key',
            'Authorization': 'Bearer ' + token
        }
    })

```

The token renewal is handled automatically in the AngularJS interceptor in the original library.  Since this isn't angular and is only using the adal base library, renewal needs to be taken care manually.  I plan on adding that but I haven't gotten around to it yet.

I'll look at adding that logic when I have some time :)

**Comment by postb99** [comment]
Sorry for jumping in but it's a related question : does the fact that the token renewal isn't handled now explain that I have trouble when starting my app with an expired token in browser ? I have set up requireAuthOnInitialize to true, then get error "AADSTS50058: A silent sign-in request was sent but no user is signed in" at this place : https://github.com/survirtual/vue-adal/blob/773c0aaac292ebf769d05dc448c26f04c2143a67/src/authentication-context.js#L61

Can I add something myself ? For example, disable requireAuthOnInitialize  and code something like in https://github.com/survirtual/vue-adal/blob/773c0aaac292ebf769d05dc448c26f04c2143a67/src/axios-http.js#L8 ?
