### ISSUE TITLE
TypeScript typings

### ISSUE THREAD

**Issue by postb99** [survirtual/vue-adal#3]
Hi,

How could you help me using your module properly? I get the following error when writing
`import Adal from 'vue-adal'`:
![image](https://user-images.githubusercontent.com/173565/38413652-9dc595fc-398c-11e8-96c2-19caa74b2daf.png)

Thanks

PS : I solved the error by simply adding the following to my `typings.d.ts`:
`declare module 'vue-adal'`, so...

**Comment by survirtual** [comment]
Hey,

This is an ES6 project, no typings for typescript at the moment!  Sorry :(

Declaring the module like you did should work in the interim.
