### ISSUE TITLE
Error when building - npm run build

### ISSUE THREAD

**Issue by jonshern** [survirtual/vue-adal#9]
When i run npm run build i get the below error.
ERROR in build.js from UglifyJs
Unexpected token: name (authenticationContext) [./node_modules/vue-adal/lib/index.js:12,0][build.js:21138,4]

When i remove vue-adal the error goes away.

**Comment by survirtual** [comment]
I'd expect bundling the babel output will fix this up; I'll see about getting rollup added here shortly, time permitting.

Manually including & transpiling will work, but sorry you had to do that!

**Comment by postb99** [comment]
I subscribe to this issue because I jumped from version 1.0 alpha 3 to 1.2.0, and despite telling babel-loader to transpile it, as I did for version 1.0, I get into troubles with IE 11 compatibility (yes...), so am looking forward a new version to understand things better :)

**Comment by survirtual** [comment]
I went ahead and added rollup to the project and published the changes to version 1.3.0 on NPM.  This should resolve everyone's issues.

I also made sure babel transpiles to include IE11 support.

Additionally, I added a pre-minified bundle:
lib/bundle.min.js

You can use that, or still uglify it yourself -- uglify should work now.

Let me know if you have any issues :)
